### ISSUE TITLE
JavaScript-Capstone

### ISSUE THREAD

**Issue by KanzaTahreem** [KanzaTahreem/JavaScript-Capstone#21]
### Hi reviewer! 👋
Here's the link of our [GitHub group project](https://github.com/users/KanzaTahreem/projects/4)

We are a team of 2 students, [Kanza](https://github.com/KanzaTahreem) and [Osvaldo](https://github.com/OsvaldoBC), and we followed the steps mentioned below for creating the project:

 Create an empty repository for your group project.
- Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects).
- Open the GitHub project (Kanban board) in your team repo.
- Make sure that in the card titles you can see: `Student A` and `Student B`
- Make sure that each card starts with `[Xpt]` - that number indicates the number of `points` that shows how complex the task is. **1 point = 1 hour of work**.
- Decide who in your team is the `Student A` and `Student B`.
- Each of the team members should assign themselves to the correct cards. Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

**Comment by BenMukebo** [comment]
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @KanzaTahreem, @OsvaldoBC,** 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- link to your GitHub project is present ✔️ 
- information about the number of people in their group  is present, keep rocking :rocket: 
- All cards with `group task` in the title is assigned to someon 👍🏻 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
